# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(635, 626)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.twMain = QtGui.QTabWidget(self.centralwidget)
        self.twMain.setGeometry(QtCore.QRect(20, 10, 591, 561))
        self.twMain.setTabsClosable(False)
        self.twMain.setMovable(False)
        self.twMain.setObjectName(_fromUtf8("twMain"))
        self.tabStamp = QtGui.QWidget()
        self.tabStamp.setObjectName(_fromUtf8("tabStamp"))
        self.cbStampCode = QtGui.QComboBox(self.tabStamp)
        self.cbStampCode.setGeometry(QtCore.QRect(110, 90, 181, 27))
        self.cbStampCode.setObjectName(_fromUtf8("cbStampCode"))
        self.btLoadStamp = QtGui.QPushButton(self.tabStamp)
        self.btLoadStamp.setGeometry(QtCore.QRect(20, 20, 271, 51))
        self.btLoadStamp.setObjectName(_fromUtf8("btLoadStamp"))
        self.leStampCode = QtGui.QLineEdit(self.tabStamp)
        self.leStampCode.setGeometry(QtCore.QRect(20, 181, 541, 27))
        self.leStampCode.setObjectName(_fromUtf8("leStampCode"))
        self.label = QtGui.QLabel(self.tabStamp)
        self.label.setGeometry(QtCore.QRect(20, 90, 81, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tabStamp)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 211, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.leStampName = QtGui.QLineEdit(self.tabStamp)
        self.leStampName.setGeometry(QtCore.QRect(110, 225, 181, 27))
        self.leStampName.setObjectName(_fromUtf8("leStampName"))
        self.label_3 = QtGui.QLabel(self.tabStamp)
        self.label_3.setGeometry(QtCore.QRect(20, 229, 91, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.sbStampPrice = QtGui.QSpinBox(self.tabStamp)
        self.sbStampPrice.setGeometry(QtCore.QRect(110, 272, 180, 27))
        self.sbStampPrice.setMaximum(999999999)
        self.sbStampPrice.setObjectName(_fromUtf8("sbStampPrice"))
        self.label_4 = QtGui.QLabel(self.tabStamp)
        self.label_4.setGeometry(QtCore.QRect(20, 276, 91, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tabStamp)
        self.label_5.setGeometry(QtCore.QRect(310, 215, 151, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.btSaveStamp = QtGui.QPushButton(self.tabStamp)
        self.btSaveStamp.setGeometry(QtCore.QRect(210, 330, 171, 71))
        self.btSaveStamp.setObjectName(_fromUtf8("btSaveStamp"))
        self.teRegulationRef = QtGui.QTextEdit(self.tabStamp)
        self.teRegulationRef.setGeometry(QtCore.QRect(310, 235, 251, 61))
        self.teRegulationRef.setObjectName(_fromUtf8("teRegulationRef"))
        self.chStampIsActive = QtGui.QCheckBox(self.tabStamp)
        self.chStampIsActive.setGeometry(QtCore.QRect(310, 300, 96, 22))
        self.chStampIsActive.setObjectName(_fromUtf8("chStampIsActive"))
        self.frame = QtGui.QFrame(self.tabStamp)
        self.frame.setGeometry(QtCore.QRect(310, 20, 251, 141))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pteStampLog = QtGui.QPlainTextEdit(self.tabStamp)
        self.pteStampLog.setGeometry(QtCore.QRect(20, 414, 551, 101))
        self.pteStampLog.setObjectName(_fromUtf8("pteStampLog"))
        self.label_7 = QtGui.QLabel(self.tabStamp)
        self.label_7.setGeometry(QtCore.QRect(22, 390, 81, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.btStampSetActivation = QtGui.QPushButton(self.tabStamp)
        self.btStampSetActivation.setGeometry(QtCore.QRect(410, 300, 151, 27))
        self.btStampSetActivation.setObjectName(_fromUtf8("btStampSetActivation"))
        self.twMain.addTab(self.tabStamp, _fromUtf8(""))
        self.tabPayment = QtGui.QWidget()
        self.tabPayment.setObjectName(_fromUtf8("tabPayment"))
        self.lePayCode = QtGui.QLineEdit(self.tabPayment)
        self.lePayCode.setGeometry(QtCore.QRect(170, 228, 271, 27))
        self.lePayCode.setObjectName(_fromUtf8("lePayCode"))
        self.label_8 = QtGui.QLabel(self.tabPayment)
        self.label_8.setGeometry(QtCore.QRect(10, 234, 91, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.leDocPath = QtGui.QLineEdit(self.tabPayment)
        self.leDocPath.setEnabled(False)
        self.leDocPath.setGeometry(QtCore.QRect(170, 10, 271, 27))
        self.leDocPath.setObjectName(_fromUtf8("leDocPath"))
        self.label_9 = QtGui.QLabel(self.tabPayment)
        self.label_9.setGeometry(QtCore.QRect(10, 14, 151, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lePayerAddress = QtGui.QLineEdit(self.tabPayment)
        self.lePayerAddress.setEnabled(False)
        self.lePayerAddress.setGeometry(QtCore.QRect(170, 118, 381, 27))
        self.lePayerAddress.setObjectName(_fromUtf8("lePayerAddress"))
        self.label_10 = QtGui.QLabel(self.tabPayment)
        self.label_10.setGeometry(QtCore.QRect(10, 122, 151, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.tabPayment)
        self.label_11.setGeometry(QtCore.QRect(10, 161, 81, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.cbStampCodePayment = QtGui.QComboBox(self.tabPayment)
        self.cbStampCodePayment.setGeometry(QtCore.QRect(170, 157, 201, 27))
        self.cbStampCodePayment.setObjectName(_fromUtf8("cbStampCodePayment"))
        self.label_12 = QtGui.QLabel(self.tabPayment)
        self.label_12.setGeometry(QtCore.QRect(10, 289, 151, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.dteTimestamp = QtGui.QDateTimeEdit(self.tabPayment)
        self.dteTimestamp.setGeometry(QtCore.QRect(170, 82, 194, 27))
        self.dteTimestamp.setObjectName(_fromUtf8("dteTimestamp"))
        self.label_13 = QtGui.QLabel(self.tabPayment)
        self.label_13.setGeometry(QtCore.QRect(10, 86, 151, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tabPayment)
        self.label_14.setGeometry(QtCore.QRect(10, 356, 151, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.teBloomFilter = QtGui.QTextEdit(self.tabPayment)
        self.teBloomFilter.setGeometry(QtCore.QRect(170, 335, 211, 61))
        self.teBloomFilter.setObjectName(_fromUtf8("teBloomFilter"))
        self.btSavePayment = QtGui.QPushButton(self.tabPayment)
        self.btSavePayment.setGeometry(QtCore.QRect(170, 410, 171, 51))
        self.btSavePayment.setObjectName(_fromUtf8("btSavePayment"))
        self.label_15 = QtGui.QLabel(self.tabPayment)
        self.label_15.setGeometry(QtCore.QRect(10, 450, 81, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.ptePaymentLog = QtGui.QPlainTextEdit(self.tabPayment)
        self.ptePaymentLog.setGeometry(QtCore.QRect(10, 470, 551, 51))
        self.ptePaymentLog.setObjectName(_fromUtf8("ptePaymentLog"))
        self.btGenPayCode = QtGui.QPushButton(self.tabPayment)
        self.btGenPayCode.setGeometry(QtCore.QRect(450, 228, 97, 27))
        self.btGenPayCode.setObjectName(_fromUtf8("btGenPayCode"))
        self.btGenDocHash = QtGui.QPushButton(self.tabPayment)
        self.btGenDocHash.setGeometry(QtCore.QRect(450, 45, 97, 27))
        self.btGenDocHash.setObjectName(_fromUtf8("btGenDocHash"))
        self.label_16 = QtGui.QLabel(self.tabPayment)
        self.label_16.setGeometry(QtCore.QRect(10, 50, 151, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.leDocHash = QtGui.QLineEdit(self.tabPayment)
        self.leDocHash.setGeometry(QtCore.QRect(170, 45, 271, 27))
        self.leDocHash.setObjectName(_fromUtf8("leDocHash"))
        self.btGetDocPath = QtGui.QPushButton(self.tabPayment)
        self.btGetDocPath.setGeometry(QtCore.QRect(450, 9, 97, 27))
        self.btGetDocPath.setObjectName(_fromUtf8("btGetDocPath"))
        self.teWordList = QtGui.QTextEdit(self.tabPayment)
        self.teWordList.setGeometry(QtCore.QRect(170, 265, 381, 61))
        self.teWordList.setObjectName(_fromUtf8("teWordList"))
        self.btGenBloomFilter = QtGui.QPushButton(self.tabPayment)
        self.btGenBloomFilter.setGeometry(QtCore.QRect(390, 335, 161, 61))
        self.btGenBloomFilter.setObjectName(_fromUtf8("btGenBloomFilter"))
        self.sbStampPricePayment = QtGui.QSpinBox(self.tabPayment)
        self.sbStampPricePayment.setEnabled(False)
        self.sbStampPricePayment.setGeometry(QtCore.QRect(270, 190, 180, 27))
        self.sbStampPricePayment.setMaximum(999999999)
        self.sbStampPricePayment.setObjectName(_fromUtf8("sbStampPricePayment"))
        self.label_17 = QtGui.QLabel(self.tabPayment)
        self.label_17.setGeometry(QtCore.QRect(170, 196, 91, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.leStampNamePayment = QtGui.QLineEdit(self.tabPayment)
        self.leStampNamePayment.setEnabled(False)
        self.leStampNamePayment.setGeometry(QtCore.QRect(378, 157, 171, 27))
        self.leStampNamePayment.setObjectName(_fromUtf8("leStampNamePayment"))
        self.twMain.addTab(self.tabPayment, _fromUtf8(""))
        self.tabPaymentHistory = QtGui.QWidget()
        self.tabPaymentHistory.setObjectName(_fromUtf8("tabPaymentHistory"))
        self.btLoadPaymentHistory = QtGui.QPushButton(self.tabPaymentHistory)
        self.btLoadPaymentHistory.setGeometry(QtCore.QRect(10, 10, 271, 51))
        self.btLoadPaymentHistory.setObjectName(_fromUtf8("btLoadPaymentHistory"))
        self.tbPaymentHistory = QtGui.QTableWidget(self.tabPaymentHistory)
        self.tbPaymentHistory.setGeometry(QtCore.QRect(10, 70, 561, 451))
        self.tbPaymentHistory.setObjectName(_fromUtf8("tbPaymentHistory"))
        self.tbPaymentHistory.setColumnCount(0)
        self.tbPaymentHistory.setRowCount(0)
        self.twMain.addTab(self.tabPaymentHistory, _fromUtf8(""))
        self.tabContentMatching = QtGui.QWidget()
        self.tabContentMatching.setObjectName(_fromUtf8("tabContentMatching"))
        self.label_18 = QtGui.QLabel(self.tabContentMatching)
        self.label_18.setGeometry(QtCore.QRect(21, 20, 91, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.btContentMatching = QtGui.QPushButton(self.tabContentMatching)
        self.btContentMatching.setGeometry(QtCore.QRect(210, 300, 161, 61))
        self.btContentMatching.setObjectName(_fromUtf8("btContentMatching"))
        self.label_19 = QtGui.QLabel(self.tabContentMatching)
        self.label_19.setGeometry(QtCore.QRect(21, 140, 151, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.teCMBloomFilter = QtGui.QTextEdit(self.tabContentMatching)
        self.teCMBloomFilter.setGeometry(QtCore.QRect(20, 40, 551, 91))
        self.teCMBloomFilter.setObjectName(_fromUtf8("teCMBloomFilter"))
        self.teCMWordList = QtGui.QTextEdit(self.tabContentMatching)
        self.teCMWordList.setGeometry(QtCore.QRect(20, 160, 551, 131))
        self.teCMWordList.setObjectName(_fromUtf8("teCMWordList"))
        self.label_20 = QtGui.QLabel(self.tabContentMatching)
        self.label_20.setGeometry(QtCore.QRect(20, 359, 81, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.pteCMResult = QtGui.QPlainTextEdit(self.tabContentMatching)
        self.pteCMResult.setGeometry(QtCore.QRect(20, 380, 551, 131))
        self.pteCMResult.setObjectName(_fromUtf8("pteCMResult"))
        self.twMain.addTab(self.tabContentMatching, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 635, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.twMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Stamp Duty", None))
        self.btLoadStamp.setText(_translate("MainWindow", "Load Data", None))
        self.label.setText(_translate("MainWindow", "Stamp Code", None))
        self.label_2.setText(_translate("MainWindow", "Stamp Code (min. 2 characters)", None))
        self.label_3.setText(_translate("MainWindow", "Stamp Name", None))
        self.label_4.setText(_translate("MainWindow", "Stamp Price", None))
        self.label_5.setText(_translate("MainWindow", "Regulation Reference", None))
        self.btSaveStamp.setText(_translate("MainWindow", "Save Data", None))
        self.chStampIsActive.setText(_translate("MainWindow", "Is Active", None))
        self.label_6.setText(_translate("MainWindow", "Statistics:", None))
        self.label_7.setText(_translate("MainWindow", "Log:", None))
        self.btStampSetActivation.setText(_translate("MainWindow", "Set Activation", None))
        self.twMain.setTabText(self.twMain.indexOf(self.tabStamp), _translate("MainWindow", "Stamp Duty", None))
        self.label_8.setText(_translate("MainWindow", "Pay Code", None))
        self.label_9.setText(_translate("MainWindow", "Document Path", None))
        self.label_10.setText(_translate("MainWindow", "Payer Address", None))
        self.label_11.setText(_translate("MainWindow", "Stamp Code", None))
        self.label_12.setText(_translate("MainWindow", "Word List (plain text)", None))
        self.label_13.setText(_translate("MainWindow", "Timestamp", None))
        self.label_14.setText(_translate("MainWindow", "Bloom Filter", None))
        self.btSavePayment.setText(_translate("MainWindow", "Make Payment", None))
        self.label_15.setText(_translate("MainWindow", "Log:", None))
        self.btGenPayCode.setText(_translate("MainWindow", "Generate", None))
        self.btGenDocHash.setText(_translate("MainWindow", "Generate", None))
        self.label_16.setText(_translate("MainWindow", "Document Hash", None))
        self.btGetDocPath.setText(_translate("MainWindow", "Choose", None))
        self.btGenBloomFilter.setText(_translate("MainWindow", "Generate Bloom Filter", None))
        self.label_17.setText(_translate("MainWindow", "Stamp Price", None))
        self.twMain.setTabText(self.twMain.indexOf(self.tabPayment), _translate("MainWindow", "Payment", None))
        self.btLoadPaymentHistory.setText(_translate("MainWindow", "Load Data", None))
        self.twMain.setTabText(self.twMain.indexOf(self.tabPaymentHistory), _translate("MainWindow", "Payment History", None))
        self.label_18.setText(_translate("MainWindow", "Bloom Filter", None))
        self.btContentMatching.setText(_translate("MainWindow", "Match", None))
        self.label_19.setText(_translate("MainWindow", "Word List (plain text)", None))
        self.label_20.setText(_translate("MainWindow", "Result:", None))
        self.twMain.setTabText(self.twMain.indexOf(self.tabContentMatching), _translate("MainWindow", "Content Matching", None))

